### ISSUE TITLE
Bug StoutTest

### ISSUE THREAD

**Issue by faseldi** [jabbalaci/PyJava#1]
StdoutTest seems not working on Windows
I haven't test if the same error is displayed on unix
Other tests are working fine.

Output :

```
Running com.github.jabbalaci.pyjava.StdoutTest
Tests run: 13, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.066 sec <<< FAILURE! - in com.github.jabbalaci.pyjava.StdoutTest
testSep(com.github.jabbalaci.pyjava.StdoutTest)  Time elapsed: 0.013 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<---[]
> but was:<---[
]
>
    at com.github.jabbalaci.pyjava.StdoutTest.testSep(StdoutTest.java:107)

testPrint(com.github.jabbalaci.pyjava.StdoutTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<[]
> but was:<[
]
>
    at com.github.jabbalaci.pyjava.StdoutTest.testPrint(StdoutTest.java:41)

testSep_2(com.github.jabbalaci.pyjava.StdoutTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<ababab[]
> but was:<ababab[
]
>
    at com.github.jabbalaci.pyjava.StdoutTest.testSep_2(StdoutTest.java:113)

testPrint_2(com.github.jabbalaci.pyjava.StdoutTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<hello[]
> but was:<hello[
]
>
    at com.github.jabbalaci.pyjava.StdoutTest.testPrint_2(StdoutTest.java:53)

testPrint_nude(com.github.jabbalaci.pyjava.StdoutTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<[]
> but was:<[
]
>
    at com.github.jabbalaci.pyjava.StdoutTest.testPrint_nude(StdoutTest.java:47)


Results :

Failed tests: 
  StdoutTest.testPrint:41 expected:<[]
> but was:<[
]
>
  StdoutTest.testPrint_2:53 expected:<hello[]
> but was:<hello[
]
>
  StdoutTest.testPrint_nude:47 expected:<[]
> but was:<[
]
>
  StdoutTest.testSep:107 expected:<---[]
> but was:<---[
]
>
  StdoutTest.testSep_2:113 expected:<ababab[]
> but was:<ababab[
]
>

Tests run: 13, Failures: 5, Errors: 0, Skipped: 0

------------------------------------------------------------------------
```

**Comment by jabbalaci** [comment]
Under Linux it's fine. I'll try it on Windows too. I think the problem is caused by the difference between the newline, i.e. "\n" vs "\r\n".

**Comment by jabbalaci** [comment]
It's corrected, the tests run on Windows too.
